### ISSUE TITLE
Faltou o package.json, desnecessário o node_modules

### ISSUE THREAD

**Issue by raupp** [BrenoJoseCoelho/ProjetoOzmap#1]
O projeto deveria ter o package.json contendo todas as bibliotecas utilizadas.
Não deveria ser feito o commit da pasta node_modules, deveria esta no .gitignore

**Comment by BrenoJoseCoelho** [comment]
As pastas node_modules foram excluídas do projeto, e o arquivo package.json, tem um pertinente a pasta server que esta dentro da mesma, e outro esta dentro da pasta interface.
