### ISSUE TITLE
Codigo erraod para retorno, 400 é bad request, user not found deveria ser 404

### ISSUE THREAD

**Issue by raupp** [BrenoJoseCoelho/ProjetoOzmap#2]
https://github.com/BrenoJoseCoelho/ProjetoOzmap/blob/aee4c2eed24a42ee2e76239cfec21dca29066add/server/api.yaml#L73

**Comment by BrenoJoseCoelho** [comment]
Feito a troca do erro tanto no userController, como no api.yaml
