### ISSUE TITLE
Não foi possivel rodar a aplicação

### ISSUE THREAD

**Issue by raupp** [BrenoJoseCoelho/ProjetoOzmap#3]
Tentei rodar a aplicação com 
npm run dev
npm run test
nenhuma delas funcionou

![image](https://user-images.githubusercontent.com/2140824/184702292-7f7840b2-3bf7-4158-93ba-6cfec16fda74.png)

**Comment by BrenoJoseCoelho** [comment]
Corrigido o que precisava para fazer o projeto rodar, tinha um erro em package.json, e foi passado no README como deve ser executado o projeto
