### ISSUE TITLE
Commites feitos na "master"

### ISSUE THREAD

**Issue by raupp** [BrenoJoseCoelho/ProjetoOzmap#6]
Não foi criado branchs e pull requests para os commits.
Commites com descrições muito simplistas, sem uma descrição do que foi feito, nem de como testar

![image](https://user-images.githubusercontent.com/2140824/184703490-0c83908c-0985-42dc-8e36-d9d4820a2729.png)

**Comment by BrenoJoseCoelho** [comment]
foi criado a release/hml, que vai servir para produzir as novas alterações que precisar e posteriormente fazer merge com a mester para depois  subir novas atualizações.
